// build.gradle.kts content with dependencies, plugins, and build configurations 
"plugins {" 
"    id(\"org.jetbrains.kotlin.android\") version \"1.9.0\" // Replace with your desired Kotlin version" 
"}" 
"allprojects {" 
"    repositories {" 
"        google()" 
"        mavenCentral()" 
"    }" 
"}" 
"plugins {" 
"    id(\"org.jetbrains.kotlin.android\") version \"1.9.0\" // Replace with your desired Kotlin version" 
"}" 
"allprojects {" 
"    repositories {" 
"        google()" 
"        mavenCentral()" 
"    }" 
"}" 
"plugins {" 
"    id(\"org.jetbrains.kotlin.android\") version \"1.9.0\" // Replace with your desired Kotlin version" 
"}" 
"allprojects {" 
"    repositories {" 
"        google()" 
"        mavenCentral()" 
"    }" 
"}" 
"plugins {" 
"    id(\"org.jetbrains.kotlin.android\") version \"1.9.0\" // Replace with your desired Kotlin version" 
"}" 
"allprojects {" 
"    repositories {" 
"        google()" 
"        mavenCentral()" 
"    }" 
"}" 
